[colors]
[colors.primary]
background = "#363849"
foreground = "#D6D1DC"

[colors.normal]
black   = "#363849"
red     = "#CDB4BC"
green   = "#9391AE"
yellow  = "#CDB4BC"
blue    = "#A6B4DE"
magenta = "#C6B2D9"
cyan    = "#A6B4DE"
white   = "#D6D1DC"

[colors.bright]
black   = "#55586B"
red     = "#C6B2D9"
green   = "#AAA0C2"
yellow  = "#D6D1DC"
blue    = "#B3C4E6"
magenta = "#AAA0C2"
cyan    = "#B3C4E6"
white   = "#D6D1DC"

[colors.cursor]
text   = "#363849"
cursor = "#D6D1DC"
